name: Cargo Publish

on:
  release:
    types: [created]

jobs:
  publish:
    name: publish ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: katyo/publish-crates@v2
      with:
        path: './formula'
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
